version: '2'
services:
  webdav:
    container_name: webdav
    image: ugeek/webdav:arm      ### ex. arm image
    ports:
      - 11080:80
    volumes:
      - /media/tong/db37ac7a-499a-4153-a849-7e3fd71891921/data:/media
    environment:
      - USERNAME=coin
      - PASSWORD=Zt123456@webdav
      - UID=1000
      - GID=1000
      - TZ=Asia/Shanghai
    networks:
      - web
    labels:
      - traefik.backend=webdav                                                                                               
      - traefik.frontend.rule=Host:webdav.your_domain.duckdns.org
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
      # Adding in secure headers
      - traefik.http.middlewares.securedheaders.headers.forcestsheader=true
      - traefik.http.middlewares.securedheaders.headers.sslRedirect=true
      - traefik.http.middlewares.securedheaders.headers.STSPreload=true
      - traefik.http.middlewares.securedheaders.headers.ContentTypeNosniff=true
      - traefik.http.middlewares.securedheaders.headers.BrowserXssFilter=true
      - traefik.http.middlewares.securedheaders.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.securedheaders.headers.stsSeconds=63072000
      - traefik.http.middlewares.securedheaders.headers.frameDeny=true
      - traefik.http.middlewares.securedheaders.headers.browserXssFilter=true
      - traefik.http.middlewares.securedheaders.headers.contentTypeNosniff=true
networks:                                                                                                                   
  web:
   external: false 

